### ISSUE TITLE
Add `CompletionItemKind#User` and `CompletionItemKind#Issue`

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10003]
### Feature Description:
Add `User` and `Issue` enum values to `CompletionItemKind. If we convert the values correctly, they should be handled by the editor.

**Comment by msujew** [comment]
I think this was already resolved by #9908

**Comment by tsmaeder** [comment]
@msujew thanks for the pointer, but the constants are missing in `theia.d.ts`, so the comparison matrix is still not green. But the fix becomes trivial, I guess.
