### ISSUE TITLE
"Unhandled Promise Rejection: no active handlers available for the command." problem in theiaide/theia-cpp Docker image

### ISSUE THREAD

**Issue by zedchance** [eclipse-theia/theia#10038]
### Bug Description:
Since Theia v.1.17.0 there has been a bug that has made the IDE unusuable.

The top menu bar is missing (File, Edit, etc), and most buttons do not work. When a button is clicked, ie the notification button in bottom right, a `Unhandled Promise Rejection` error is printed in the console. This problem was not here in Theia v.1.16.0.

<img width="968" alt="Screen Shot 2021-09-01 at 12 57 37 PM" src="https://user-images.githubusercontent.com/41851969/131735807-70348212-5c01-486b-99d6-42a66e7f68c9.png">

This screenshot shows the top menu bar missing.

When a button is clicked, ie the notification button, this is printed to the console:

```
[Error] Unhandled Promise Rejection: Error: The command 'notifications.commands.toggle' cannot be executed. There are no active handlers available for the command.
	(anonymous function) (bundle.js:2:1803688)
	asyncFunctionResume
	(anonymous function) (bundle.js:2:1681222)
	s (bundle.js:2:5935815)
	p (bundle.js:2:5935958)
	(anonymous function) (bundle.js:2:5936104)
	A (bundle.js:2:5936185)
	ot (bundle.js:2:5951654)
	nt (bundle.js:2:5951467)
	at (bundle.js:2:5951821)
	ht (bundle.js:2:5953028)
	B (bundle.js:2:6049806)
	G (bundle.js:2:5937509)
	Zt (bundle.js:2:5958983)
	Qt (bundle.js:2:5958201)
	Qt
	(anonymous function) (bundle.js:2:6255696)
	L (bundle.js:2:6049584)
	$t (bundle.js:2:5958016)
	$t
```

### Steps to Reproduce:

Run Theia v1.17.1 `theiaide/theia-cpp:1.17.1` Docker image with this command ([found here](https://github.com/theia-ide/theia-apps/blob/master/theia-cpp-docker/README.md)):

```
docker run --security-opt seccomp=unconfined --init -it -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia-cpp:1.17.1
```

When visiting `localhost:3000`, note that the top menu bar is missing.
Note console errors when trying to click a button, ie notification button (bell icon in bottom right).

This problem does **not** happen on Theia v.1.16.0 (can test by using `theiaide/theia-cpp:1.16.0` image).

### Additional Information

When the container starts, I notice some errors that have to do with `bundle.js`:

```
root ERROR h@http://localhost:3000/bundle.js:2:1670388
i@http://localhost:3000/bundle.js:2:1924342
i@[native code]
http://localhost:3000/bundle.js:2:5173836
http://localhost:3000/bundle.js:2:5175751
http://localhost:3000/bundle.js:2:5159161
c@http://localhost:3000/bundle.js:2:5174242
http://localhost:3000/bundle.js:2:5175166
map@[native code]
http://localhost:3000/bundle.js:2:5159161
getContributions@http://localhost:3000/bundle.js:2:1807737
onStart@http://localhost:3000/bundle.js:2:1802394
http://localhost:3000/bundle.js:2:1458274
asyncFunctionResume@[native code]
http://localhost:3000/bundle.js:2:1457520
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
root ERROR h@http://localhost:3000/bundle.js:2:1670388
i@http://localhost:3000/bundle.js:2:1924342
i@[native code]
http://localhost:3000/bundle.js:2:5173836
http://localhost:3000/bundle.js:2:5175751
http://localhost:3000/bundle.js:2:5159161
c@http://localhost:3000/bundle.js:2:5174242
http://localhost:3000/bundle.js:2:5175166
map@[native code]
http://localhost:3000/bundle.js:2:5159161
getContributions@http://localhost:3000/bundle.js:2:1807737
http://localhost:3000/bundle.js:2:1470206
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

See the entire log of starting the container [here](https://gist.github.com/zedchance/f30adadfd5eaee833002e6dcc17ac0b3)

- Operating System: macOS 11.5.2, Docker Desktop 4.0.0, Docker Engine v20.10.8
- Theia Version: v.1.17.1

**Comment by msujew** [comment]
Hi @zedchance, this has been addressed by #10034, please update to Theia v1.17.2 which was released recently.

**Comment by zedchance** [comment]
Thanks for responding @msujew, I just tried the `theiaide/theia-cpp:1.17.2` image and the problem still persists.

**Comment by vince-fugnitto** [comment]
@zedchance can you confirm by removing `@theia/cpp-debug` from your dockerfile for test purposes, I have a feeling that since it targets the older `es5` it causes issues on startup.

**Comment by vince-fugnitto** [comment]
I confirmed the issue is caused by `@theia/cpp-debug` which targets `es5`.

**Comment by zedchance** [comment]
@vince-fugnitto, yes I can also confirm that removing `@theia/cpp-debug` from my `package.json` has fixed the issue. I noticed in #10042 that you have a fix incoming, thanks for the help!

**Comment by vince-fugnitto** [comment]
Thank you for reporting the issue, I've opened the upstream https://github.com/theia-ide/theia-apps/issues/494 to track the fix in the docker images :+1:
