### ISSUE TITLE
Cannot Open Terminal on Windows Remote

### ISSUE THREAD

**Issue by parisa-mchp** [eclipse-theia/theia#14348]
### Bug Description:

On linux, after building the theia electron application, and connecting to a windows server over SSH, terminal widgets can be created, but cannot be interacted with.

### Steps to Reproduce:

1. On linux, build and launch the theia electron app using the following commands (taken from [here](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md))

```sh
git clone https://github.com/eclipse-theia/theia \
    && cd theia \
    && yarn \
    && yarn download:plugins \
    && yarn browser build \
    && yarn browser start
```

2. Using the command `SSH: Connect Current Window to Host...` connect to a windows server.
3. Once connected, use `Terminal: Create New Integrated Terminal from a Profile` and select the `cmd` profile.
4. A new terminal should be created, but it's output should be blank. Furthermore clicking on the terminal doesn't allow you to type in it.

![{86FC3A9A-9C91-40AF-8064-CFA993DC29D1}](https://github.com/user-attachments/assets/6cceb9cd-4584-4db7-914b-96c0b88c1c1e)

### Additional Information

Although building the IDE locally causes this issue, it works fine if using the [prepackaged appimage](https://www.eclipse.org/downloads/download.php?file=/theia/ide/latest/linux/TheiaIDE.AppImage&r=1). I wanted to test building the appimage locally to see if this addresses the issue, but couldn't figure out how to do this. It's mentioned in the [documentation ](https://theia-ide.org/docs/blueprint_documentation) that the `yarn electron package` command does this, but looking at `example/electron/package.json` this command doesn't seem to exist. More information on this would be appreciated as well.

- Operating System: Ubuntu 22.04.2 LTS (WSL)
- Theia Version: 1.54.0

**Comment by tsmaeder** [comment]
@msujew ?

**Comment by msujew** [comment]
Hey @parisa-mchp,

> It's mentioned in the [documentation ](https://theia-ide.org/docs/blueprint_documentation)that the yarn electron package command does this, but looking at example/electron/package.json this command doesn't seem to exist.

You're looking in the wrong repo. See [here](https://github.com/eclipse-theia/theia-ide/blob/1fc2fc267893586d146581dcd0b979a89cbd5018/applications/electron/package.json#L146)

@jfaltermeier @sgraband I can see that the native dependencies packaging job hasn't been executed in some time. See [here](https://github.com/eclipse-theia/theia/actions/workflows/native-dependencies.yml). I'm on the road right now, so I cannot confirm, but I assume the native dependencies we publish in our recent releases for Windows are outdated.

**Comment by parisa-mchp** [comment]
> You're looking in the wrong repo. See [here](https://github.com/eclipse-theia/theia-ide/blob/1fc2fc267893586d146581dcd0b979a89cbd5018/applications/electron/package.json#L146)

@msujew Oh I see. Thanks for pointing that out.

**Comment by jfaltermeier** [comment]
> You're looking in the wrong repo. See [here](https://github.com/eclipse-theia/theia-ide/blob/1fc2fc267893586d146581dcd0b979a89cbd5018/applications/electron/package.json#L146)
> 
> @jfaltermeier @sgraband I can see that the native dependencies packaging job hasn't been executed in some time. See [here](https://github.com/eclipse-theia/theia/actions/workflows/native-dependencies.yml). I'm on the road right now, so I cannot confirm, but I assume the native dependencies we publish in our recent releases for Windows are outdated.

Yes, that's true, it's not currently included in the publishing instructions: https://github.com/eclipse-theia/theia/blob/master/doc/Publishing.md#publishing. Should we add this to the guide for each release?

**Comment by JonasHelming** [comment]
@msujew ?

**Comment by parisa-mchp** [comment]
Hi there, has anyone had an opportunity to look at this issue yet? Thanks!

**Comment by msujew** [comment]
@parisa-mchp This should be resolved for 1.55.0. Have you had a chance to test this for the latest release?

**Comment by parisa-mchp** [comment]
@msujew That's good to know. Unfortunately I'm still seeing the same issue. This is only when build from this repo, from `theia-ide` it works fine. Is it working on your end?

![image](https://github.com/user-attachments/assets/dbf878c5-1b5d-4aa9-82e3-7ee37fb72e73)

**Comment by parisa-mchp** [comment]
@msujew Hey, I tested again on 1.57.0 and am still seeing the issue. I was wondering if you could confirm that it's working on your end.

**Comment by parisa-mchp** [comment]
Okay I've looked into the issue more closely. It seems like `node-pty` is built differently on linux than on windows. If you're connecting to a windows server from a linux machine, it will copy to the server the wrong version of `node-pty` which causes the terminal issues seen above. I'm looking into potential fixes for this.
