### ISSUE TITLE
1.55.1 Community release has inversify runtime errors

### ISSUE THREAD

**Issue by tortmayr** [eclipse-theia/theia#14652]
### Bug Description:
Theia products using the current community release (1.55.1) fail to start due to an inversify error.
This is caused by a breaking change introduced with inversify `6.1.x`.
For Theia `>= 1.56` this is fixed with https://github.com/eclipse-theia/theia/pull/14435.
This change should probably be backported to ensure that the community release is working.
Currently adopters need to manually lock the version via resolutions as a workaround.

### Steps to Reproduce:

1. Use the yeoman generator to generate a new example project (yo theia-extension -> hello world)
2. Manually change the theia versions in the browser/electron package.json to `1.55.1`
3. Build with `yarn && yarn build:browser`
4. Start with `yarn start:browser`
5. The start will fail with the following error:

```console
❯ yarn start:browser  
yarn run v1.22.22
$ yarn --cwd browser-app start
$ theia start
Error: The number of constructor arguments in the derived class NodeStopwatch must be >= than the number of constructor arguments of its base class.
    at /home/tobias/temp/test-theia/browser-app/lib/backend/vendors-node_modules_theia_core_lib_common_index_js.js:25822:27
    at Array.forEach (<anonymous>)
    at _createSubRequests (/home/tobias/temp/test-theia/browser-app/lib/backend/vendors-node_modules_theia_core_lib_common_index_js.js:25801:20)
    at /home/tobias/temp/test-theia/browser-app/lib/backend/vendors-node_modules_theia_core_lib_common_index_js.js:25826:17
    at Array.forEach (<anonymous>)
    at /home/tobias/temp/test-theia/browser-app/lib/backend/vendors-node_modules_theia_core_lib_common_index_js.js:25825:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (/home/tobias/temp/test-theia/browser-app/lib/backend/vendors-node_modules_theia_core_lib_common_index_js.js:25801:20)
    at plan (/home/tobias/temp/test-theia/browser-app/lib/backend/vendors-node_modules_theia_core_lib_common_index_js.js:25847:9)
    at /home/tobias/temp/test-theia/browser-app/lib/backend/vendors-node_modules_theia_core_lib_common_index_js.js:25011:46
```

### Additional Information

- Operating System:
- Theia Version:

@jfaltermeier @sgraband FYI

**Comment by tsmaeder** [comment]
This issue reveals a general problem we have in that we can't prevent adopters from picking up updates to dependencies that fit our version expressions. Another instance of this problem is https://github.com/eclipse-theia/theia/issues/14586.
I don't think it's a good policy to backport fixes each time an updated dependency might break adopters. We would be investing sometimes a lot of time for something that can be trivally fixed by adding a yarn resolution to the adopters product package.json. So unless you can argue that this case is special, IMO a message to @theia-dev is the right "fix". 
In the context of the scrollbar issue, I've been thinking that maybe we should have a dedicated channel for adopters where such issues may be communicated.

**Comment by sdirix** [comment]
I generally agree with @tsmaeder that preventing this kind of breakage entirely may not be feasible, and we should focus on documenting and communicating such occurences effectively.

That said, if a fix for an ongoing issue is available, I believe there’s a strong case for backporting it to the latest community release to enhance the adopter experience as long as the effort required is reasonable.

Let’s include this in the agenda for the next dev meeting to discuss further.

**Comment by dmm9** [comment]
I have just come across the same issue after having to recreate the *.lock file. I have fixed it with `"resolutions": { "**/inversify": "6.0.2" }` in the top package.json of my app.

Currently, theia relies "too much" on the idea that breaking changes are only introduced with mayor versions, so the dependencies in package.json's are usually declared with a caret (^). But this is not always the case. I think it would be a good idea to pin a specific version of inversify in the dependencies of theia/core. So `"inversify": "x.y.z"`, instead of `"inversify": "^x.y.z"`. This is more future-proof.

**Comment by tsmaeder** [comment]
@dmm9 the trouble is that we'd have to manually update the versions if we fix them. And the problem is not solved for dependencies that themselves attract modules via a lenient expression.
