### ISSUE TITLE
Toolbar style loading is not normal

### ISSUE THREAD

**Issue by zhangzejun123** [eclipse-theia/theia#15922]
### Bug Description:

After updating to the latest theia-ide version, I found that the ToolBar style is abnormal and I cannot add tools.

### Steps to Reproduce:

1.Install the latest version of TheiaIde
2.open it
3. I found that all styles of the toolbar are abnormal, such as the mouse animation is missing. And an error will be reported when adding a tool

![Image](https://github.com/user-attachments/assets/52ac199c-de83-44b8-ae68-39a3c924033b)

### Additional Information

- Operating System: windows 10
- Theia Version: 1.62.2

**Comment by rschnekenbu** [comment]
@zhangzejun123, thanks for your report. I can indeed reproduce the issue on the navigation icons not being properly enabled / disabled on 1.62 and 1.63 on the theia examples. The mouse cursor does not change also when hovering the different tool icons (compared with 1.58.5 for example).
Please note that with 1.63 (incoming release), creating the command in the toolbar shall no longer display an error message.  see https://github.com/eclipse-theia/theia/issues/15231

**Comment by Hanksha** [comment]
Hi, the mouse cursor issue is fixed by #15948

**Comment by zhangzejun123** [comment]
> Hi, the mouse cursor issue is fixed by [#15948](https://github.com/eclipse-theia/theia/pull/15948)

It seems that there is indeed no problem with the style, but from the modified code, it seems that the problem of solving component refresh still exists. For example, when using go-back, the go-forward button of the navigation is still unavailable.

**Comment by Hanksha** [comment]
@zhangzejun123 Yes I noticed that as well (see Follow-ups section on my PR), the toolbar items are not updated when the enablement changes (like when you use go back/forward) and you can still click disabled items too. I think it'll have to be addressed separately.

**Comment by zhangzejun123** [comment]
> [@zhangzejun123](https://github.com/zhangzejun123) Yes I noticed that as well (see Follow-ups section on my PR), the toolbar items are not updated when the enablement changes (like when you use go back/forward) and you can still click disabled items too. I think it'll have to be addressed separately.

OK, I read your PR carefully and understand

**Comment by ndoschek** [comment]
I’m closing this now that #15948 has been merged. Feel free to reopen it if you disagree.
