### ISSUE TITLE
"files.exclude" setting is not merged between different scopes as it done in vscode

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#16255]
### Bug Description:
Hi,

VS Code merges settings from all scopes, with lower scopes overriding higher ones:
 - Folder settings override Workspace settings.
 - Workspace settings override User settings.

So the effective files.exclude is the union of all keys, but if the same key (same glob) appears in multiple scopes, the value from the most specific scope wins.
In VS Code in general, object-type settings (like files.exclude) are merged key by key.
Primitive settings (boolean, string, number) are overridden entirely by the more specific scope.

In Theia, the files.exclude setting does not merge correctly between user and workspace settings. Instead, the last modified setting overrides the other. For example, if I update files.exclude in the workspace settings, and then in the user settings, the user setting completely overrides the workspace one, rather than merging the two.
This behavior seems unintended and could lead to confusion or loss of configuration.

### Steps to Reproduce:

1. Update the files.exclude in workspace settings
2. Update the files.exclude in user settings, same keys and new ones.
3. See that the user scope wins!!!

### Additional Information

- Operating System: Mac
- Theia Version: Theia 1.64 (also on old ones)

**Comment by tsmaeder** [comment]
@safisa can you reproduce this in Theia master? We just merged a large change in the area of preferences. Also: do you have a scenario how to observe the behavior in the UI?

**Comment by safisa** [comment]
Hi @tsmaeder,
I rechecked it in master, and I see there is a change, but still not doing the correct merge of object keys.
I see now that the last modified files exclude issue is not happening anymore. The Workspace scope overrides the user scope always, but the main issue still exists, since it overrides the whole object definition (files.exclude) and does not override the specific key in the object as it is done in vscode).

Here is a straightforward scenario to reproduce:
1. Open the user settings files, and add this: "files.exclude": {
        "folderA": true,
        "folderB": true
    }
2. Open the workspace settings files, and add this: "files.exclude": {
        "folderB": false,
        "folderC": true
    }
3. Check the file explorer tree, you will see folders folderA and folderB, in vscode you will see only folderB.
4. The correct resolution of excluded files should be: {
    "folderA": true,
    "folderB": false,
    "folderC": true
}

Note that this is true for all object-type settings, not only for files.exclude.

Thanks

**Comment by safisa** [comment]
Hi @tsmaeder ,

I see that the merge method in the PreferenceUtils works as expected. But the real issue is in the onFilesPreferenceChanged in the FileNavigatorFilter class.
Instead of doing this: 
`this.filterPredicate = this.createFilterPredicate(newValue as FileNavigatorFilter.Exclusions | undefined || {});`

Replace it with the following to fix the issue:

```
 const filesExcludes = this.filesPreferences['files.exclude'];
 this.filterPredicate = this.createFilterPredicate(filesExcludes);
```

WDYT?
