### ISSUE TITLE
fix fs path accesses in the plugin system

### ISSUE THREAD

**Issue by fiurthorn** [eclipse-theia/theia#4213]
Get this message on windows when i try to start a hosted server for development.

```
root ERROR Uncaught Exception:  Error: Invalid listen argument: [ 6789, 3030 ]
root ERROR Error: Invalid listen argument: [ 6789, 3030 ]
    at Server.listen (net.js:1501:9)
    at BackendApplication.<anonymous> (c:\fiurthorn\workspace\toolbox\data\runtime\theia\node_modules\@theia\core\lib\node\backend-application.js:273:32)
    at step (c:\fiurthorn\workspace\toolbox\data\runtime\theia\node_modules\@theia\core\lib\node\backend-application.js:59:23)
    at Object.next (c:\fiurthorn\workspace\toolbox\data\runtime\theia\node_modules\@theia\core\lib\node\backend-application.js:40:53)
    at c:\fiurthorn\workspace\toolbox\data\runtime\theia\node_modules\@theia\core\lib\node\backend-application.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (c:\fiurthorn\workspace\toolbox\data\runtime\theia\node_modules\@theia\core\lib\node\backend-application.js:30:12)
    at BackendApplication.start (c:\fiurthorn\workspace\toolbox\data\runtime\theia\node_modules\@theia\core\lib\node\backend-application.js:217:16)
    at c:\fiurthorn\workspace\toolbox\data\runtime\theia\src-gen\backend\server.js:34:28
    at <anonymous>
root ERROR Failed to load plugin metadata from "/c:/fiurthorn/workspace/theia-hello-world-plugin/" Error: ENOENT: no such file or directory, open 'c:\c:\fiurthorn\workspace\theia-hello-world-plugin\package.json'
Hosted instance has been terminated
```

```
@theia/core 0.4.0-testnext.d1b1bc8c
@theia/output 0.4.0-testnext.d1b1bc8c
@theia/process 0.4.0-testnext.d1b1bc8c
@theia/filesystem 0.4.0-testnext.d1b1bc8c
@theia/variable-resolver 0.4.0-testnext.d1b1bc8c
@theia/workspace 0.4.0-testnext.d1b1bc8c
@theia/languages 0.4.0-testnext.d1b1bc8c
@theia/editor 0.4.0-testnext.d1b1bc8c
@theia/navigator 0.4.0-testnext.d1b1bc8c
@theia/markers 0.4.0-testnext.d1b1bc8c
@theia/outline-view 0.4.0-testnext.d1b1bc8c
@theia/monaco 0.4.0-testnext.d1b1bc8c
@theia/callhierarchy 0.4.0-testnext.d1b1bc8c
@theia/file-search 0.4.0-testnext.d1b1bc8c
@theia/git 0.4.0-testnext.d1b1bc8c
@theia/json 0.4.0-testnext.d1b1bc8c
@theia/merge-conflicts 0.4.0-testnext.d1b1bc8c
@theia/messages 0.4.0-testnext.d1b1bc8c
@theia/mini-browser 0.4.0-testnext.d1b1bc8c
@theia/console 0.4.0-testnext.d1b1bc8c
@theia/terminal 0.4.0-testnext.d1b1bc8c
@theia/debug 0.4.0-testnext.d1b1bc8c
@theia/userstorage 0.4.0-testnext.d1b1bc8c
@theia/preferences 0.4.0-testnext.d1b1bc8c
@theia/task 0.4.0-testnext.d1b1bc8c
@theia/plugin-ext 0.4.0-testnext.d1b1bc8c
@theia/preview 0.4.0-testnext.d1b1bc8c
@theia/search-in-workspace 0.4.0-testnext.d1b1bc8c
@theia/textmate-grammars 0.4.0-testnext.d1b1bc8c
@theia/typescript 0.4.0-testnext.d1b1bc8c
```

**Comment by akosyakov** [comment]
We should make sure that we always use `FileUri.fsPath` on backend and `FilesSystem.getFsPath` on frontend to retrieve fs paths from URIs in the `@theia/plugin-ext` and `@theia/plugin-ext-vscode`, otherwise it is not going to work on Windows.

**Comment by akosyakov** [comment]
@fiurthorn Could you investigate further? PRs are always very welcomed.

**Comment by fiurthorn** [comment]
Tested on Windiws Linux Subsystem omit the windows Path Exception,
but keep failing to start the hosted Workspace

```
root ERROR Failed to start the backend application.
root ERROR TypeError [ERR_INVALID_ARG_VALUE]: The argument 'options' must have the property "port" or "path". Received [ 6786, 3030 ]
    at Server.listen (net.js:1429:11)
```

**Comment by fiurthorn** [comment]
tried following fix at backend-application.js@224:32 to get it working:

```
port = aPort !== undefined ? aPort : this.cliParams.port;
* port = Array.isArray(port) ? port[port.length - 1] : port
```

**Comment by akosyakov** [comment]
Regarding this error:

> root ERROR Failed to load plugin metadata from "/c:/fiurthorn/workspace/theia-hello-world-plugin/" Error: ENOENT: no such file or directory, open 'c:\c:\fiurthorn\workspace\theia-hello-world-plugin\package.json'

You can start investigation here: https://github.com/theia-ide/theia/blob/a2fa90401638148b5fd1f713d096db46e0a8aa80/packages/plugin-ext/src/hosted/node/plugin-reader.ts#L93

And inspect how do you get such bogus path.

**Comment by akosyakov** [comment]
The start command for a hosted server is created here: 
https://github.com/theia-ide/theia/blob/a2fa90401638148b5fd1f713d096db46e0a8aa80/packages/plugin-ext/src/hosted/node/hosted-instance-manager.ts#L240

It would be interesting to debug it and see a reason for `Error: Invalid listen argument: [ 6789, 3030 ]`.

Check the debug view, there are configuration to debug the backend.

**Comment by akosyakov** [comment]
@fiurthorn Could you give a try again? Many places have been fixed during this year.

**Comment by fiurthorn** [comment]
Great to hear that, but i do not have installed THEIA these days during many problems from update to update. 
I thinks it's a nice project and I come when it is more stable.

**Comment by davide-sergi** [comment]
@akosyakov hi, I still having problems using theia.Uri.fsPath on Windows. 
For example when I try to create a folder, I got: UNKNOWN , unknown error, mkdir "\\file\to\path"
 (please not without 'c:')

I'm using fs node library in a backend plugin - running on electron theia app-  in order to interact with filesystem of host windows machine .

**Comment by akosyakov** [comment]
@davide-sergi Could you open a new issue please? with a bit of more context, i.e maybe vscode extension or theia plugin to reproduce?
