### ISSUE TITLE
Input gets into wrong editor

### ISSUE THREAD

**Issue by a1994846931931** [eclipse-theia/theia#5489]
### Description
 

It seems that the editor that is opened from "Find All Reference" is not regarded as the current editor and, hence, the input is wrongly directed into the former editor.

### Reproduction Steps

![editor-wrong](https://user-images.githubusercontent.com/17487291/59585841-f9a11380-9113-11e9-9700-47bf54c538f5.gif)

**OS and Theia version:**
OS: linux

**Diagnostics:**

**Comment by 32leaves** [comment]
I also have this problem without the editor preview. It seems to appear whenever saving a file takes a long time (e.g. with some Go files). Then the input goes in the file that I previously edited and which is taking a long time to save.

**Comment by 502647092** [comment]
@akosyakov 
![temp](https://user-images.githubusercontent.com/10203793/59894942-23f51880-9415-11e9-9453-872fb506153e.gif)
first input any content in editor
ant input something in other area like `search` `debug  console` `find command`
then press `Ctrl + Z` to Undo
the editor content will be undo

**Comment by 502647092** [comment]
@akosyakov 
When can this problem be fixed?

**Comment by akosyakov** [comment]
https://github.com/theia-ide/theia/issues/5489#issuecomment-504273083 is it related, undo is based on last focused editor? I would say it is expected.

The issues is about moving focus from one editor to another editor, but changes are still applied to previously focused editor. I still struggle to reproduce it with editors only without editor previews and other widgets.

**Comment by 502647092** [comment]
@akosyakov 
yes
but I input at search widgets then is still undo latest editor
I think it should exec undo at latest input area(like search) not only editor

**Comment by caseyflynn-google** [comment]
@akosyakov I am unable to repro this against master, is this resolved?

**Comment by akosyakov** [comment]
@caseyflynn-google for the editor preview I fixed it during Monaco migration, for plain editor i could not reproduce it before, so probably we can close it till someone can come up with reproducible example

**Comment by 502647092** [comment]
@akosyakov widgets still have this problem

- input some thing in main editor
- `Ctrl + F` open search at editor
- input some thing in search widgets
- `Ctrl + Z` undo input
- search widgets nothing happend but main editor undo it

**Comment by a1994846931931** [comment]
@akosyakov Yeah, I can't reproduce it either. 

@502647092 's looks more like another problem.

**Comment by 502647092** [comment]
ok i open a new issues
