### ISSUE TITLE
[navigator] some icons & names are not aligned 

### ISSUE THREAD

**Issue by fangnx** [eclipse-theia/theia#5580]
As the screenshot shows, icons and labels of `package.json` and `README.md` are not aligned properly.

![image](https://user-images.githubusercontent.com/25921074/60131456-71e88400-9767-11e9-8e71-8e836f271124.png)

**Comment by vince-fugnitto** [comment]
I wonder if we should think about dropping our `file-icon.js` support for the vscode's icons.
https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons

https://code.visualstudio.com/blogs/2016/09/08/icon-themes

It's not only our vertical spacing that is off but also our horizontal (notice the 'README' label is pushed more to the right than other files).

<div align='center'>

<img width="425" alt="Screen Shot 2019-06-25 at 9 27 57 PM" src="https://user-images.githubusercontent.com/40359487/60144931-547cdf80-9792-11e9-9b0c-91b581abb23e.png">


</div>

**Comment by fangnx** [comment]
> I wonder if we should think about dropping our `file-icon.js` support for the vscode's icons.
> https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons
> 
> https://code.visualstudio.com/blogs/2016/09/08/icon-themes
> 
> It's not only our vertical spacing that is off but also our horizontal (notice the 'README' label is pushed more to the right than other files).
> 
> <img alt="Screen Shot 2019-06-25 at 9 27 57 PM" width="425" src="https://user-images.githubusercontent.com/40359487/60144931-547cdf80-9792-11e9-9b0c-91b581abb23e.png">

Seems like the icons all have different width and length. Is it because we used icons from vs code but did not resize them?

**Comment by vince-fugnitto** [comment]
I think in general it's how the icons are, they have their own height and width which may differ and we give them all consistent font-sizes, so in the end the icons are not properly normalized to each other.

**Comment by kaiyue0329** [comment]
I think this issue is already fixed.

**Comment by vince-fugnitto** [comment]
> I think this issue is already fixed.

Unfortunately it is still an issue :(
See how the filenames are not aligned (this happens due to the alignment of icons)

![image](https://user-images.githubusercontent.com/40359487/73183343-a6029980-40e8-11ea-9313-32a4dc02826a.png)
